name: 'Argument Counter'
description: 'Count # of arguments passed in'
inputs:
  arguments-to-count:
    description: 'argument to count'
    required: true
    default: ''
outputs:
  arg-count:
    description: 'Count of arguments passed in'
    value: ${{ steps.return-result.outputs.num-args }}
runs:
  using: "composite"
  steps:
    - name: Print arguments if any
      run: |
        echo Arguments: ${{ inputs.arguments-to-count }}.
      shell: bash
    - name: Give execute permission to the script
      run: |
        chmod +x ${{ github.action_path }}/count-args.sh
      shell: bash
    - id: return-result
      run: |
        echo "num-args=`${{ github.action_path }}/count-args.sh ${{ inputs.arguments-to-count }}`" >> $GITHUB_OUTPUT
      shell: bash
