name: debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "::debug::This is a debug message"
          echo "::warning::This is a warning message"
          echo "::notice::This is a notice message"
          echo "::error::This is a error message"
          echo "::error file=debug.yml,line=15,col=1,endColumn=2::This is a error message"

      - run: |
          echo "::group::Extend ifo"
          echo "Info line 1"
          echo "Info line 2"
          echo "Info line 3"
          echo "::endgroup::"
