# Workflow to demo installing a package an executing on a self-hosted runner

name: file tree

on:
  workflow_dispatch:

jobs:
  file-tree:
    runs-on: self-hosted
    steps:
    - name: Print working directory
      run: pwd
    - name: List directory
      run: dir
    - name: Execute tree
      run: Get-ChildItem -Recurse | Tee-Object -FilePath "C:\study\actions-runner\filetreelist.txt"
