name: use output

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
#      build-stage: ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}
      artifact-tag: ${{ steps.changelog.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set debug
        id: set-debug-stage
        run: echo "BUILD_STAGE=debug" >> $GITHUB_OUTPUT

      - name: Get stage
        run: echo "The build stage is ${{ steps.set-debug-stage.outputs.BUILD_STAGE }}"

      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.14.0

      - name: Set artifact-tag output
        run: echo "artifact-tag=${{ steps.changelog.outputs.version }}" 
 
  report:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Get stage
        env:
          BUILD_STAGE: ${{ needs.setup.outputs.build-stage }}
          ARTIFACT_TAG: ${{ needs.setup.outputs.artifact-tag }}
        run: |
          echo "The build stage is $BUILD_STAGE"
          echo "The artifact tag is $ARTIFACT_TAG"
