name: Create issues across prods and levels

on:
  workflow_dispatch:

jobs:
  create-new-issue:
    strategy:
      max-parallel: 3
      fail-fast: true
      matrix:
        prod: [prod1, prod2]
        level: [dev, stage, rel]
        include:
          - prod: prod3
            level: dev
            tag: alpha
        exclude:
          - prod: prod1
            level: stage
          - level: dev
    uses: xxxxxseed/common/.github/workflows/create-repo-issue3.yml@main
    secrets: inherit
    with:
      title: "${{ matrix.prod }} issue"
      body: "Update for ${{ matrix.level }}"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: |
          echo "outputs: ${{ toJson(needs.create-new-issue.outputs) }}"
          echo "Issue number: ${{ needs.create-new-issue.outputs.issue-num }}"
