name: use reusable workflow3

on:
  workflow_dispatch:

jobs:
  create-new-issue:
    uses: xxxxxseed/common/.github/workflows/create-repo-issue3.yml@main
    secrets: inherit
    with:
      title: "Test issue"
      body: "Test body"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: |
          echo "outputs: ${{ toJson(needs.create-new-issue.outputs) }}"
          echo "Issue number: ${{ needs.create-new-issue.outputs.issue-num }}"
