name: use reusable workflow

on:
  workflow_dispatch:

jobs:
  issue:
    uses: xxxxxseed/common/.github/workflows/create-repo-issue.yml@main
    secrets:
      token: ${{ secrets.WORKFLOW_USE }}
    with:
      title: "Test issue"
      body: "Test body"
