name: use cache

on:
  workflow_dispatch:

jobs:
  create_cache_key:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          pwd
          ls
      
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")"
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        id: cache
        with:
          path: /test
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Check for cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: |
          echo "Got cache hit on key"
