name: Create issues across prods

on:
  workflow_dispatch:

jobs:
  create-new-issue:
    strategy:
      matrix:
        prod: [prod1, prod2]
    uses: xxxxxseed/common/.github/workflows/create-repo-issue3.yml@main
    secrets: inherit
    with:
      title: "${{ matrix.prod }} issue"
      body: "Update for a level"

  report-issue-number:
    runs-on: ubuntu-latest
    needs: create-new-issue
    steps:
      - run: |
          echo "outputs: ${{ toJson(needs.create-new-issue.outputs) }}"
          echo "Issue number: ${{ needs.create-new-issue.outputs.issue-num }}"
