name: use custom action

on:
  workflow_dispatch:
    inputs:
      myValues:
        description: 'Input Values'

jobs:
  count-args:
    runs-on: ubuntu-latest
    steps:
      - id: report-count
        uses: xxxxxseed/github-actions@main
        with:
          arguments-to-count: ${{ github.event.inputs.myValues }}
      - shell: bash
        run: |
          echo "argument count is ${{ steps.report-count.outputs.arg-count }}"
